/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLogEntry {
  'action' : string,
  'fabricName' : string,
  'userId' : string,
  'timestamp' : bigint,
  'quantity' : number,
  'rackId' : string,
}
export type ExternalBlob = Uint8Array;
export interface FabricInventoryEntry {
  'fabricName' : string,
  'purchaseDate' : [] | [bigint],
  'billPhoto' : [] | [ExternalBlob],
  'fabricPhoto' : [] | [ExternalBlob],
  'quantity' : number,
  'rackId' : string,
}
export interface UpdateFabricData {
  'fabricName' : string,
  'purchaseDate' : [] | [bigint],
  'billPhoto' : [] | [ExternalBlob],
  'fabricPhoto' : [] | [ExternalBlob],
  'quantity' : number,
  'rackId' : string,
}
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFabricEntry' : ActorMethod<
    [
      string,
      {
        'fabricName' : string,
        'purchaseDate' : [] | [bigint],
        'billPhoto' : [] | [ExternalBlob],
        'fabricPhoto' : [] | [ExternalBlob],
        'quantity' : number,
      },
    ],
    string
  >,
  'adjustQuantity' : ActorMethod<[string, number], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, string], string>,
  'createUser' : ActorMethod<[Principal, string, string, string], string>,
  'getAllInventoryFabricEntries' : ActorMethod<
    [],
    Array<[string, FabricInventoryEntry]>
  >,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAuditLog' : ActorMethod<[], Array<AuditLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventory' : ActorMethod<[], Array<[string, FabricInventoryEntry]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteToMasterAdmin' : ActorMethod<
    [{ 'username' : string, 'name' : string }],
    string
  >,
  'removeFabricEntry' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFabricEntry' : ActorMethod<[string, UpdateFabricData], string>,
  'updateFabricQuantity' : ActorMethod<[string, number], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];